export const GET_ALL_PRESENTATIONS = "GET_ALL_PRESENTATIONS";
export const ADD_PRESENTATION = "ADD_PRESENTATION";
export const EDIT_PRESENTATION = "EDIT_PRESENTATION";
export const DELETE_PRESENTATION = "DELETE_PRESENTATION";

// export const GET_ONE_PRESENTATION = "GET_ONE_PRESENTATION";
